### ISSUE TITLE
Allow settings secrets with files

### ISSUE THREAD

**Issue by dezren39** [terranix/terranix#104]
Hi I use sops and am wondering the best way to set secrets for providers, and possibly other use cases. It would be nice if I could set a provider api key by providing a file, but maybe there's other ways to handle this?

for now i am using the sops provider to get the secrets for my other providers, but haven't tried setting this up with terranix yet.

**Comment by mrVanDalo** [comment]
Terranix only renders json files which get picked up by terraform.

If you want to use sops you should use the sops terraform provider. Otherwise your secrets end up world readable in the nix store.

You should be able to use the sops provider like every other provider in terranix.
