### ISSUE TITLE
Empty objects shouldn't be converted to nulls

### ISSUE THREAD

**Issue by KarolisL** [terranix/terranix#18]
When creating a [GCP VM](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage) with ephemeral public IP, we must set `access_config` to an empty object:

```hcl
  network_interface {
    network = "default"

    access_config {
      // Ephemeral public IP
    }
  }
```

Unfortunately, terranix renders `"access_config": null` in the resulting json, thus creating a VM without public IP.
As a workaround, I was able to come up with this:
```nix
{
     # ......
      network_interface = {
        network = "default";

        access_config = {
          # Ephemeral public IP
          nat_ip = null; # <-- setting it to null
        };
      };
     # ......
}
```

It might be more explicit (on the other hand, it might look like there's no nat_ip at all), but it is cumbersome. There are things you need to *know* when translating HCL to Nix. I suppose it would be more user friendly to just translate to empty object? Would it break anyone's config?

Probably related to https://github.com/terranix/terranix/issues/4 ?

**Comment by mrVanDalo** [comment]
Is fixed on `develop` branch, will be in the next release.

**Comment by KarolisL** [comment]
Thank you!
