### ISSUE TITLE
export AST

### ISSUE THREAD

**Issue by mrVanDalo** [terranix/terranix#25]
in #24  @terlar opened the question on exporting the terranix generated terraform config AST and the terranix-doc-json generated AST, for further manipulation.

@terlar I guess you mean something like this : 
```nix
      lib.terranixConfigurationAst =
        { system ? ""
        , pkgs ? builtins.getAttr system nixpkgs.outputs.legacyPackages
        , extraArgs ? { }
        , modules ? [ ]
        , strip_nulls ? true
        }:
        let
          terranix_args = {
            inherit pkgs extraArgs strip_nulls;
            terranix_config.imports = modules;
          };
        in
          import ./core/default.nix terranix_args;
```

and

```nix
      lib.terranixOptionsAst =
        { system ? ""
        , pkgs ? builtins.getAttr system nixpkgs.outputs.legacyPackages
        , modules ? [ ]
        , moduleRootPath ? "/"
        , urlPrefix ? ""
        , urlSuffix ? ""
        }:
        import ./lib/terranix-doc-json.nix {
            terranix_modules = modules;
            inherit moduleRootPath urlPrefix urlSuffix pkgs;
        };
```

right? What do you think about the naming?

**Comment by terlar** [comment]
Yes, this is great, I couldn’t come up with a better name myself, I was thinking about using “raw” or “nix”, but doesn’t really feel right. I think “ast” could work.

**Comment by mrVanDalo** [comment]
https://github.com/terranix/terranix/blob/feature/ast/flake.nix < how would you use that in a `nix repl`?

**Comment by terlar** [comment]
Did you link correctly (the defaultApp/test)?

You can evaluate it like this:
```
nix-repl> :b (builtins.getFlake "github:terranix/terranix/feature/ast").defaultApp.x86_64-linux
```

or inside the same project use `builtins.getFlake (toString ./.)`

Or what are you asking more specifically?

When it comes to the AST functions I could explore the result via the REPL either via tab-completion or various functions.

**Comment by mrVanDalo** [comment]
Version 2.5.2 come with ast functions.
(Documented here : https://terranix.org/documentation/flakes/#using-terranixconfigurationast-or-terranixconfigurationast)

**Comment by terlar** [comment]
Thank you.

I notice the title in the docs is wrong. It says `terranixConfigurationAst` twice instead of `terranixConfigurationAst` and `terranixOptionsAst`
