### ISSUE TITLE
Way to create and consume tf modules?

### ISSUE THREAD

**Issue by srhb** [terranix/terranix#44]
Once infra gets big, I kind of want to be able to deploy smaller bits of it to reduce blast radius. This is traditionally done with terraform modules, but using those with terranix doesn't seem trivial. Is there a good way to do this? Is there another way to split up "logical" infra without resorting to direct resource targeting?

Or better yet; how, in general, do people deal with big (100s-1000s of resources) with terranix?

**Comment by mrVanDalo** [comment]
You should be able to use terraform modules. I did not document that (yet), but modules you should be able to do this:

```
{ ... }:
{
  module.vpc = {
    source = "terraform-aws-modules/vpc/aws";
    name = "my-vpc";
    cidr = "10.0.0.0/16";
    azs = [ "eu-west-1a" "eu-west-1b" "eu-west-1c" ];
    private_subnets = [ "10.0.1.0/24" "10.0.2.0/24" "10.0.3.0/24" ];
    public_subnets = [ "10.0.101.0/24" "10.0.102.0/24" "10.0.103.0/24" ];
    enable_nat_gateway = true;
    enable_vpn_gateway = true;
    tags.terranix = true;
  };
}
```

Alternatively/Additionally you are able to [use the nixos-module-system](https://terranix.org/documentation/modules/).

But to reduce the "blast radius" I avoid defining the whole infrastructure in one run. Instead I define multiple runs which depend sequentially on each other. I get a lot of inspiration from https://www.terraform-best-practices.com/code-structure

For example I create these folders, each representing one run (`terraform apply`):
```
development-00-network 
development-10-stateful-resources-team-a
development-11-stateful-resources-team-b
development-20-cluster
development-30-services-team-a
development-31-services-team-b
staging-00-network 
staging-10-stateful-resources-team-a
staging-11-stateful-resources-team-b
staging-20-cluster
staging-30-services-team-a
staging-31-services-team-b
```
This would manage 2 environments. To import state from another run I use [data "terraform_remote_state"](https://registry.terraform.io/providers/hashicorp/terraform/latest/docs/data-sources/remote_state)

I'm not a fan of `terraform apply -target=...` 
I'm not a fan of [terraform workspaces](https://developer.hashicorp.com/terraform/language/state/workspaces#using-workspaces), in every project I've seen they add complexity and provoke mistakes.

This is how I manage it in terraform and I would do it in terranix (if I would find a customer who would allow me to use terranix :D) Hope I could help.

**Comment by srhb** [comment]
That makes sense, thank you. I guess I'm mostly floundering a bit because I find it hard to tie that idea together with using terranix as declaratively as possible. (generating multiple "infrastructures" and applying them, while passing back outputs to Nix, etc.)

I'll try to go with the directory idea and see if I can make terranix do this in a satisfactory way. Thanks again for the ideas.
