### ISSUE TITLE
Any example creating multiple resources in loop?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [terranix/terranix#48]
I want to create 3 static IPs and then attach to 3 VMs.

**Comment by mrVanDalo** [comment]
You can for example use the `count` variable of terraform. I'm not sure about the `foreach` keywords of HCL, must try first. But of course you can use the nix way to do it.

```nix
resource = mapAttrs (name: value: {
  aws_instance."example_${name}" = {
    name = "example_${name}";
    instance_type = value;
  };
  aws_eip."lb_${name}" = {
    instance = "\${aws_instance.example_${name}}";
  };
}) { 1 = "t2.micro"; 2 = "t2.medium"; 3 = "t3.medium"; }  ;
```

**Comment by mrVanDalo** [comment]
You can check out : 
https://terranix.org/documentation/functions/ and https://terranix.org/documentation/terranix-vs-hcl/ for more information.
